Wasit.Dashboard/Controllers/PropertyManagementController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Wasit.Core.Enums;
using Wasit.Services.Interfaces.Dashboard;

namespace Wasit.Dashboard.Controllers
{
    public class PropertyManagementController : Controller
    {
        private readonly IDPropertyManagementService _propertyManagementService;
        private readonly IToastNotification _toastNotification;

        public PropertyManagementController(IDPropertyManagementService propertyManagementService, IToastNotification toastNotification)
        {
            _propertyManagementService = propertyManagementService;
            _toastNotification = toastNotification;
        }



        #region Rent Management
        public async Task<IActionResult> RentManagement()
        {
            var result = await _propertyManagementService.RentManagementRequests();
            return View(result);
        }


        [HttpPut]
        public async Task<IActionResult> AcceptRentManagementRequest(long id)
        {
            var result = await _propertyManagementService.AcceptRentManagementRequest(id);
            return Json(result);
        }


        [HttpDelete]
        public async Task<IActionResult> RejectRentManagementRequest(long id)
        {
            var result = await _propertyManagementService.RejectRentManagementRequest(id);
            return Json(result);
        }


        public async Task<IActionResult> RentManagementRequestDetails(long id)
        {
            var result = await _propertyManagementService.RentManagementRequestDetails(id);

            if (result is null)
                return NotFound();

            return View(result);
        }
        #endregion



        #region Maintenance Management
        public async Task<IActionResult> MaintenanceManagement(RentalManagementOrderStatus status = RentalManagementOrderStatus.New)
        {
            var data = await _propertyManagementService.MaintainanceManagementRequests(status);
            return View(data);
        }
        #endregion

    }
}

Wasit.Dashboard/Views/PropertyManagement/MaintenanceManagement.cshtml
@model IEnumerable<Wasit.Services.ViewModels.PropertyManagement.MaintainanceMangement.MaintainanceManagementRequestViewModel>
@{
    ViewData["Title"] = "طلبات الصيانة";
}


<div class="filter-nav d-flex justify-content-center flex-row list-group">
    <button class="list-group-item active" id="pills-new-tab" data-bs-toggle="pill" data-bs-target="#new" type="button" value="1" role="tab">جديدة</button>
    <button class="list-group-item" id="pills-current-tab" data-bs-toggle="pill" data-bs-target="#current" type="button" value="2" role="tab">حالية</button>
    <button class="list-group-item" id="pills-finished-tab" data-bs-toggle="pill" data-bs-target="#finished" type="button" value="3" role="tab">منتهية</button>
</div>
<div class="tab-content" id="pills-tabContent">

    <div class="tab-pane fade show active" id="new" role="tabpanel">
        <table id="" class="data-table responsive nowrap" width="100%">
            <thead>
                <tr class="table-head">
                    <th class="text-center p-3">اسم العميل</th>
                    <th class="text-center">رقم الجوال</th>
                    <th class="text-center">تفاصيل العقار</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Where(x => x.Status == RentalManagementOrderStatus.New))
                {
                    <tr class="table-row">
                        <td>@item.UserName</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.EstateName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="tab-pane fade" id="current" role="tabpanel">
        <table id="" class="data-table responsive nowrap" width="100%">
            <thead>
                <tr class="table-head">
                    <th class="text-center p-3">اسم العميل</th>
                    <th class="text-center">رقم الجوال</th>
                    <th class="text-center">تفاصيل العقار</th>
                    <th class="text-center">اسم المندوب</th>
                    <th class="text-center">جوال المندوب </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Where(x => x.Status == RentalManagementOrderStatus.Current))
                {
                    <tr class="table-row">
                        <td>@item.UserName</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.EstateName</td>
                        <td>@item.DelegateName</td>
                        <td>@item.DelegatePhone</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="tab-pane fade" id="finished" role="tabpanel">
        <table id="" class="data-table responsive nowrap" width="100%">
            <thead>
                <tr class="table-head">
                    <th class="text-center p-3">اسم العميل</th>
                    <th class="text-center">رقم الجوال</th>
                    <th class="text-center">تفاصيل العقار</th>
                    <th class="text-center">اسم المندوب</th>
                    <th class="text-center">جوال المندوب </th>
                    <th class="text-center">تقييم العميل</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Where(x => x.Status == RentalManagementOrderStatus.Finished))
                {
                    <tr class="table-row">
                        <td>@item.UserName</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.EstateName</td>
                        <td>@item.DelegateName</td>
                        <td>@item.DelegatePhone</td>
                        <td>
                            <div class="d-flex align-items-center justify-content-center">
                                <p class="font-xs m-0 mx-2"><span>@item.Rating</span>/5</p>
                                <i class="fa-solid fa-star star"></i>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>


@section scripts {
    <script>
        $(document).ready(function () {
            $(".dt-search input").attr("placeholder", `بحث باسم العميل - رقم الجوال -  تفاصيل العقار `);

            // $('.data-table').DataTable({
            //     responsive: {
            //         details: {
            //             renderer: DataTable.Responsive.renderer.listHiddenNodes()
            //         },
            //     },
            //     pageLength: 6,
            //     fixedHeader: {
            //         header: false,
            //     },
            //     searching: false,
            //     sort: false,
            //     bInfo: false,
            // });
        });
    </script>
}

Wasit.Dashboard/Views/PropertyManagement/RentManagement.cshtml
@model IEnumerable<Wasit.Services.ViewModels.PropertyManagement.RentManagement.RentManagementRequestViewModel>
@{
    ViewData["Title"] = "ادراة الايجارات";
}

<table id="" class="data-table responsive nowrap" width="100%">
    <thead>
        <tr class="table-head">
                <th class="text-center p-3">اسم العميل</th>
                <th class="text-center">بيانات العقار</th>
                <th class="text-center">مبلغ العقار</th>
                <th class="text-center"></th>
                <th class="text-center">الحالة</th>
            </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="table-row">
                <td>@item.UserName</td>
                <td>@item.PropertyName</td>
                <td>@item.UniqueNumber</td>
                <td>
                    <div class="d-flex justify-content-center">
                        <a asp-controller="PropertyManagement" asp-action="RentManagementRequestDetails" asp-route-id="@item.Id" class="edit-btn w-auto">التفاصيل</a>
                    </div>
                </td>
                <td class="text-center">
                    <div class="d-flex gap-3 justify-content-center">
                        @if (item.IsPending)
                        {
                            <a onclick="Accept(@item.Id,this)" class="accept-btn">قبول</a>
                            <button class="delete-btn" data-bs-toggle="modal" data-bs-target="#delete" onclick="PassId('@item.Id')">رفض</button>
                        }
                        else
                        {
                            <span class="text-success">@item.Status</span>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>


<!--delete Modal Start -->
    <div class="modal fade" id="delete" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="filterLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title font-bold font-b" id="filterLabel">رفض الطلب</h5>
                    <button type="button" class="btn-close m-0" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <p class="font-xs">هل تريد رفض الطلب ؟</p>
                </div>
                <div class="modal-footer">
                    <span hidden ></span>
                    <button type="button" class="secondary-btn w-100 py-3" onclick="Reject(this)" >تأكيد الرفض </button>
                </div>
            </div>
        </div>
    </div>
    <!--delete modal End-->


@section scripts {
    <script>


        $(document).ready(function () {
            $(".dt-search input").attr("placeholder", `بحث باسم العميل - بيانات العقار -  مبلغ العقار `);
        });

        function PassId(requestId) {
            $('#delete span').text(requestId);
        }

        function Accept(requestId,btn) {
            $(btn).attr('disabled', true);
            $.ajax({
                url: "/PropertyManagement/AcceptRentManagementRequest",
                type: "PUT",
                dataType: "json",
                data: {
                    id: requestId
                },
                success: function (result) {
                    toastr.success('تم قبول الطلب بنجاح');
                    setInterval(function () { window.location.href = "/PropertyManagement/RentManagement" }, 2000);
                },
                failure: function (info) {
                    toastr.error('حدث خطأ ما');
                }
            });
          }

        function Reject(btn) {
            $(btn).attr('disabled', true);
            var requestId = $(btn).siblings('span').text();
            $("#delete").modal('hide');
            $.ajax({
                url: "/PropertyManagement/RejectRentManagementRequest",
                type: "DELETE",
                dataType: "json",
                data: {
                    id: requestId
                },
                success: function (result) {
                    toastr.success('تم رفض الطلب بنجاح');
                    setInterval(function () { window.location.href = "/PropertyManagement/RentManagement" }, 2000);
                },
                failure: function (info) {
                    toastr.error('حدث خطأ ما');
                }
            });
          }
    </script>
}

Wasit.Dashboard/Views/PropertyManagement/RentManagementRequestDetails.cshtml
@model Wasit.Services.ViewModels.PropertyManagement.RentManagement.RentManagementRequestDetailsViewModel
@{
    ViewData["Title"] = "تفاصيل العقار";
}

<style>
    <link rel="stylesheet" href="~/plugins/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css" >
</style>

<div class="row mb-5">
    <div class="col-lg-6 .col-md-12 .col-12">
        <div>
            <!-- Carousel Big -->
            <div class="product-carousel owl-carousel owl-theme position-relative" id="big">
                <img src="@Model.Image" alt="" class="pro-slide-img md">
            </div>            
        </div>
        <!--  -->
    </div>
    <div class="col-lg-6 .col-md-12 .col-12 mt-3">
        <div class="d-flex justify-content-between align-items-center">
            <h5 class="font-b font-sm mb-4">@Model.Name</h5>
        </div>
        <div class="location d-flex justify-content-between flex-wrap gap-2 w-100 mb-3">
            <div class="d-flex justify-content-center align-items-center">
                <img class="mx-1" src="imgs/location.png" alt="">
                <p class="m-0 font-xs text-secondary">@Model.Address</p>
            </div>
            <p class="font-xs m-0 text-secondary"> <span class="dark-blue">@Model.UniqueNumber</span>:الرقم المرجعي</p>
            <p class="font-xs m-0 text-secondary">عدد الشقق : <span class="dark-blue">@Model.ApartmentsCount</span></p>
        </div>
        <div class="d-flex justify-content-between flex-wrap gap-2 w-100 mb-3">
            <p class="text-secondary font-xs">اسم المستخدم : <span class="dark-blue">@Model.UserName</span></p>
        </div>
    </div>
</div>
<table id="" class="data-table responsive nowrap" width="100%">
    <thead>
        <tr class="table-head">
            <th class="text-center p-3">اسم الشقة</th>
            <th class="text-center">رقم الشقة</th>
            <th class="text-center">تاريخ الدفع</th>
            <th class="text-center">قيمة الايجار</th>
            <th class="text-center"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Apartments)
        {
            <tr class="table-row">
                <td>@item.Name</td>
                <td>@item.Number</td>
                <td>@item.PaymentDate</td>
                <td>@item.Value ريال</td>
                <td>
                    <p class="text-danger">@item.IsPaid</p>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
    <script src="plugins/OwlCarousel2-2.3.4/dist/owl.carousel.min.js"></script>
    <script>
        $(document).ready(function () {
            var bigimage = $("#big");
            var thumbs = $("#thumbs");
            var syncedSecondary = true;

            bigimage
                .owlCarousel({
                    items: 1,
                    loop: true,
                    rtl: true,
                    nav: false,
                    dots: false,
                    autoplay: true,
                    margin: 8,
                    autoplayTimeout: 5000,
                    autoplaySpeed: 1500,
                    smartSpeed: 1500,
                    slideSpeed: 2000,
                    responsiveRefreshRate: 200,
                })
                .on("changed.owl.carousel", syncPosition);

            thumbs
                .on("initialized.owl.carousel", function () {
                    thumbs
                        .find(".owl-item")
                        .eq(0)
                        .addClass("current");
                })
                .owlCarousel({
                    items: 2,
                    rtl: true,
                    dots: false,
                    nav: false,
                    margin: 5,
                    smartSpeed: 500,
                    // slideSpeed: 500,
                    slideBy: 4,
                    responsiveRefreshRate: 100,
                    responsive: {
                        1200: {
                            items: 4,
                        },
                        992: {
                            items: 3,
                        },
                        768: {
                            items: 4,
                        },
                        375: {
                            items: 3,
                        },
                    }
                })
                .on("changed.owl.carousel", syncPosition2);
            function syncPosition(el) {
                var count = el.item.count - 1;
                var current = Math.round(el.item.index - el.item.count / 2 - 0.5);
                if (current < 0) {
                    current = count;
                }
                if (current > count) {
                    current = 0;
                }
                //to this
                thumbs
                    .find(".owl-item")
                    .removeClass("current")
                    .eq(current)
                    .addClass("current");
                var onscreen = thumbs.find(".owl-item.active").length - 1;
                var start = thumbs
                    .find(".owl-item.active")
                    .first()
                    .index();
                var end = thumbs
                    .find(".owl-item.active")
                    .last()
                    .index();
                if (current > end) {
                    thumbs.data("owl.carousel").to(current, 100, true);
                }
                if (current < start) {
                    thumbs.data("owl.carousel").to(current - onscreen, 100, true);
                }
            }
            function syncPosition2(el) {
                if (syncedSecondary) {
                    var number = el.item.index;
                    bigimage.data("owl.carousel").to(number, 100, true);
                }
            }
            thumbs.on("click", ".owl-item", function (e) {
                e.preventDefault();
                var number = $(this).index();
                bigimage.data("owl.carousel").to(number, 300, true);
            });
        });
    </script>
}